unique_ids:
  forms:
    Hello_Form: AAPHLQCDQJARPJYFD7XTAAPSWIU2IWU6
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: 4CAKXAREVWWG3R23L3JGIAD3OUW25WOU
    theme.css: BL54NTG4ALYX2AVO4YCPURWD7PNBGVLM
  scripts: {}
